Revert "x86 idle: EXPORT_SYMBOL(default_idle, pm_idle) only when APM demands it"
This reverts commit 06ae40ce073daf233607a3c54a489f2c1e44683e.

Causes a build failure on i386.  Revert until official fix from
upstream.

ERROR: "pm_idle" [arch/x86/kernel/apm.ko] undefined!
ERROR: "default_idle" [arch/x86/kernel/apm.ko] undefined!

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>