(drop after 2.6.39-rc1) [media] staging: altera-jtag needs delay.h
altera-jtag.c needs to include <linux/delay.h> to fix a build error:

drivers/staging/altera-stapl/altera-jtag.c:398: error: implicit declaration of function 'udelay'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Igor M. Liplianin <liplianin@netup.ru>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>
(cherry picked from commit 92ce52695ccf2b6c4ef7eb02e1bee1bcbf5fde89)

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>