UBUNTU: fix ERROR: __devcgroup_inode_permission undefined
Fix build error:

  ERROR: "__devcgroup_inode_permission" [ubuntu/aufs/aufs.ko] undefined!

Result of upstream commit:

  commit 482e0cd3dbaa70f2a2bead4b5f2c0d203ef654ba
  Author: Al Viro <viro@zeniv.linux.org.uk>
  Date:   Sun Jun 19 13:01:04 2011 -0400

    devcgroup_inode_permission: take "is it a device node" checks to inlined wrapper

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>