UBUNTU: [Config] Disable CONFIG_FT1000 on powerpc64-smp
Build failure:

drivers/staging/ft1000/ft1000-pcmcia/ft1000_hw.c:2293:1: error:
__ksymtab_stop_ft1000_card causes a section type conflict

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>